//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BookstoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService")]
    [System.SerializableAttribute()]
    public partial struct Result : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BookstoreServiceReference.Status StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BookstoreServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService")]
    [System.SerializableAttribute()]
    public partial struct Book : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookstoreServiceReference.IBookstoreService")]
    public interface IBookstoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/AddBook", ReplyAction="http://tempuri.org/IBookstoreService/AddBookResponse")]
        Client.BookstoreServiceReference.Result AddBook(string bookAddProtocolText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/AddBook", ReplyAction="http://tempuri.org/IBookstoreService/AddBookResponse")]
        System.Threading.Tasks.Task<Client.BookstoreServiceReference.Result> AddBookAsync(string bookAddProtocolText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBookPrice", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBookPriceResponse")]
        Client.BookstoreServiceReference.Result UpdateBookPrice(string priceUpdateProtocolText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBookPrice", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBookPriceResponse")]
        System.Threading.Tasks.Task<Client.BookstoreServiceReference.Result> UpdateBookPriceAsync(string priceUpdateProtocolText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        Client.BookstoreServiceReference.GetBooksResponse GetBooks(Client.BookstoreServiceReference.GetBooksRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        System.Threading.Tasks.Task<Client.BookstoreServiceReference.GetBooksResponse> GetBooksAsync(Client.BookstoreServiceReference.GetBooksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksRequest {
        
        public GetBooksRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Client.BookstoreServiceReference.Book[] GetBooksResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Client.BookstoreServiceReference.Result result;
        
        public GetBooksResponse() {
        }
        
        public GetBooksResponse(Client.BookstoreServiceReference.Book[] GetBooksResult, Client.BookstoreServiceReference.Result result) {
            this.GetBooksResult = GetBooksResult;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookstoreServiceChannel : Client.BookstoreServiceReference.IBookstoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookstoreServiceClient : System.ServiceModel.ClientBase<Client.BookstoreServiceReference.IBookstoreService>, Client.BookstoreServiceReference.IBookstoreService {
        
        public BookstoreServiceClient() {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.BookstoreServiceReference.Result AddBook(string bookAddProtocolText) {
            return base.Channel.AddBook(bookAddProtocolText);
        }
        
        public System.Threading.Tasks.Task<Client.BookstoreServiceReference.Result> AddBookAsync(string bookAddProtocolText) {
            return base.Channel.AddBookAsync(bookAddProtocolText);
        }
        
        public Client.BookstoreServiceReference.Result UpdateBookPrice(string priceUpdateProtocolText) {
            return base.Channel.UpdateBookPrice(priceUpdateProtocolText);
        }
        
        public System.Threading.Tasks.Task<Client.BookstoreServiceReference.Result> UpdateBookPriceAsync(string priceUpdateProtocolText) {
            return base.Channel.UpdateBookPriceAsync(priceUpdateProtocolText);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.BookstoreServiceReference.GetBooksResponse Client.BookstoreServiceReference.IBookstoreService.GetBooks(Client.BookstoreServiceReference.GetBooksRequest request) {
            return base.Channel.GetBooks(request);
        }
        
        public Client.BookstoreServiceReference.Book[] GetBooks(out Client.BookstoreServiceReference.Result result) {
            Client.BookstoreServiceReference.GetBooksRequest inValue = new Client.BookstoreServiceReference.GetBooksRequest();
            Client.BookstoreServiceReference.GetBooksResponse retVal = ((Client.BookstoreServiceReference.IBookstoreService)(this)).GetBooks(inValue);
            result = retVal.result;
            return retVal.GetBooksResult;
        }
        
        public System.Threading.Tasks.Task<Client.BookstoreServiceReference.GetBooksResponse> GetBooksAsync(Client.BookstoreServiceReference.GetBooksRequest request) {
            return base.Channel.GetBooksAsync(request);
        }
    }
}
